apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - runtimeclass.yaml
  - rbac.yaml
  - quotas.yaml
  - networkpolicies.yaml
  - postgres.yaml
  - sandbox-api.yaml
  - bot.yaml
