name: house-chatbot

services:
  deployment-bot:
    image: ghcr.io/bushshrub/housebot:latest
    command: ["deployment-bot"]
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMELAB_DEPLOY_PATH:-.}:/deployment
    environment:
      - DEPLOYMENT_PATH=/deployment
      - DOCKER_NETWORK=house-chatbot_default
