{{- if not .Values.sandboxApi.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "housebot.sandboxApi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "housebot.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "housebot.sandboxApi.token" . | b64enc | quote }}
{{- end }}
